name: Publish

on:
  push:
    branches:
      - semantic

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Build documentation
        run: yarn build:docs

      - name: Publish
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_SEMANTIC_RELEASE }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish documentation
        # if: steps.semantic.outputs.new_release_published == 'true'
        uses: docker://decathlon/wiki-page-creator-action:latest
        env:
          ACTION_MAIL: test@users.noreply.github.com
          ACTION_NAME: test
          GH_PAT: ${{ secrets.GH_TOKEN_SEMANTIC_RELEASE }}
          MD_FOLDER: docs
          OWNER: binance-chain-npm
          REPO_NAME: js-sdk-docs
